language: node_js
node_js:
- "stable"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn lint
- yarn build
- yarn test
after_success:
- cat ./coverage/lcov.info | yarn coveralls
cache:
  directories:
  - "node_modules"
deploy:
  provider: npm
  email: "s.i.grishchenko@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true