language: node_js
node_js:
  - "11"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn workspaces run build
  - yarn lint
  - yarn compile
  - yarn test
after_success:
  - cat ./coverage/lcov.info | yarn coveralls
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: >-
    yarn config set _authToken $NPM_AUTH_TOKEN &&
    yarn workspace reselect-utils publish --non-interactive --tag alpha
  on:
    tags: true