language: node_js
node_js:
- "11"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn workspaces run build
- yarn lint
- yarn compile
- yarn test
after_success:
- cat ./coverage/lcov.info | yarn coveralls
cache:
  directories:
  - "node_modules"
deploy:
  provider: script
  script: yarn workspace reselect-utils publish --non-interactive --tag alpha
  skip_cleanup: true
  on:
    tags: true