language: node_js
node_js:
  - "12"
script:
  - yarn workspaces run build
  - yarn lint
  - yarn compile
  - yarn test
after_success:
  - cat ./coverage/lcov.info | yarn coveralls
cache:
  directories:
    - "node_modules"
before_deploy:
  - yarn site
deploy:
  - provider: script
    script: >-
      yarn config set _authToken $NPM_AUTH_TOKEN &&
      yarn workspace reselect-utils publish --non-interactive --tag beta
      yarn workspace eslint-plugin-reselect-utils publish --non-interactive --tag beta
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: site
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
